### ISSUE TITLE
Time is not changed issue in Viva registration - Student Side

### ISSUE THREAD

**Issue by RamithaHeshan33** [Cyber-III/Student-Management-System#175]
**Describe the bug**

Students can register for their viva sessions on the Student's Viva Registration page. The registration process worked well on the first day (Day 01, from 9:00 AM to 4:00 PM). However, on the second day, all registrations are limited to the time slot from 9:00 AM to 9:15 AM, and the time cannot be changed.

**Screenshots**

![Screenshot 2024-06-19 002443](https://github.com/Cyber-III/Student-Management-System/assets/142712365/00ec8609-9712-4d6a-adf3-c479b6792831)

Look here, everything is fine till 16.00 on 21-06-2024. Even if the date changes after that, the time will not change

**Are you working on it**
No

**Comment by NusrathCassim** [comment]
I was able to adjust the date after making changes to submit.php, however the problem with the time remains.

![Screenshot 2024-06-18 231545](https://github.com/Cyber-III/Student-Management-System/assets/154523455/e7183219-b1ee-43e1-a5d9-0be8f90636e0)

**Comment by NusrathCassim** [comment]
I am still looking into the PHP code. to find out where it went wrong.
