### ISSUE TITLE
Set a tittle logo on the tab

### ISSUE THREAD

**Issue by RamithaHeshan33** [Cyber-III/Student-Management-System#68]
**Describe your feature**

Let's add a logo on the tab on every page

**Describe the solution that you suggest**

Let's add a logo on the tab on every page

**Screenshots**

![Screenshot 2024-05-31 200212](https://github.com/Cyber-III/Student-Management-System/assets/142712365/6d6efa87-9648-40c4-942e-e7c59b729c3c)

update like this
![Screenshot 2024-05-31 200307](https://github.com/Cyber-III/Student-Management-System/assets/142712365/102da79c-6538-41f6-b9cb-23af53ce11a5)

**Are you working on it?**
No

**Comment by Sathinmanitha** [comment]
@RamithaHeshan33 Please Assign me for this issue..

**Comment by RamithaHeshan33** [comment]
Sure. @Sathinmanitha. Please be sure to consider all pages should have this logo on their tab
