### ISSUE TITLE
Update the template's Navbar

### ISSUE THREAD

**Issue by RamithaHeshan33** [Cyber-III/Student-Management-System#69]
**Describe your feature**

Update the Navbar Home and Logout buttons. 

**Describe the solution that you suggest**

Please update the color to blue.

**Screenshots**

![Screenshot 2024-05-31 200544](https://github.com/Cyber-III/Student-Management-System/assets/142712365/c5bf640e-d2d9-4594-8886-27eb961228c9)

**Are you working on it?**
No

**Comment by Sathinmanitha** [comment]
@RamithaHeshan33 Please Assign me for this issue..
