### ISSUE TITLE
job application apply error (vacancies page)

### ISSUE THREAD

**Issue by AbhithaVish** [Cyber-III/Student-Management-System#97]
**Describe the bug**

There was a error in job application apply. all others are working properly except first vacancie.

**Describe the Solution**

**Screenshots**

Error
![job application apply error](https://github.com/Cyber-III/Student-Management-System/assets/162031145/ace399ce-7373-4a81-8b37-fa7d6e3fd6bf)

other vacancies (Others are working properly)

![job application apply error (only in first one)](https://github.com/Cyber-III/Student-Management-System/assets/162031145/c03975e5-5d5a-40d7-8a7a-65c91d5f89a6)

**Are you working on it**
No

**Comment by RamithaHeshan33** [comment]
https://github.com/Cyber-III/Student-Management-System/assets/142712365/b4af3da4-0fb7-4b0e-af58-fc4df58fefcb

Though the error is gone, there is still an issue when the user applies for the same vacancy like this. Can you please fix this issue @Sathinmanitha ?

**Comment by Sathinmanitha** [comment]
@RamithaHeshan33 Okay
