### ISSUE TITLE
Class Schedule page need to be in upper section in the Templete

### ISSUE THREAD

**Issue by AbhithaVish** [Cyber-III/Student-Management-System#98]
**Describe the bug**

Class Schedule page need to be in upper section in the Template. Because class schedule is now in between "Assignments" and "Results", second thing is class schedule is the most using function in this system. therefor it should be in an upper section where user can easily access. (like after the payment)

**Describe the Solution**

Move class schedule function after the payment function

**Screenshots**

![Class schedule needed to be up](https://github.com/Cyber-III/Student-Management-System/assets/162031145/2eb3f0dd-1800-4521-8a2b-d38af131a2a3)

**Are you working on it**
Yes

**Comment by AbhithaVish** [comment]
@RamithaHeshan33  Assign this to me

**Comment by RamithaHeshan33** [comment]
> @RamithaHeshan33 Assign this to me

It should be updated like this

-Student
-Payment
-Class Schedule
-Exam
-Assignment
-Results
-Noticeboard
-Library Books
-Graduation
-Memberships
-Modules
-Materials
-Guidelines
-Message
-Call Center
-Lec Evaluation
-Vacancies

**Comment by AbhithaVish** [comment]
> > @RamithaHeshan33 Assign this to me
> 
> It should be updated like this
> 
> -Student -Payment -Class Schedule -Exam -Assignment -Results -Noticeboard -Library Books -Graduation -Memberships -Modules -Materials -Guidelines -Message -Call Center -Lec Evaluation -Vacancies

sure.
